import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";

const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const encoder=new TextEncoder();
type Json=Record<string,any>; type Environment="ote"|"production";
class HttpError extends Error{constructor(public status:number,public code:string,message:string,public details?:unknown){super(message)}}
const clean=(v:unknown)=>String(v??"").trim();const money=(v:unknown)=>Math.round((Number(v)||0)*100)/100;
function cors(req:Request):HeadersInit{const origin=req.headers.get("origin");let allow="*";if(origin){try{const h=new URL(origin).hostname.toLowerCase();if(h==="domain.kmerhosting.com"||h==="localhost"||h==="127.0.0.1"||h.endsWith(".vercel.app"))allow=origin;}catch{}}return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, apikey, content-type, idempotency-key","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8","Vary":"Origin","X-Content-Type-Options":"nosniff"};}
const json=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors(req)});
async function sha256(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(v)));return Array.from(d).map(b=>b.toString(16).padStart(2,"0")).join("");}
function pathOf(req:Request){const p=new URL(req.url).pathname,m="/domain-wallet",i=p.indexOf(m);return(i>=0?p.slice(i+m.length):p).replace(/\/+$/,"")||"/";}
async function body(req:Request){if(!req.headers.get("content-type")?.includes("application/json"))throw new HttpError(415,"unsupported_media_type","Content-Type application/json is required.");const p=await req.json().catch(()=>null);if(!p||Array.isArray(p)||typeof p!=="object")throw new HttpError(400,"invalid_json","A JSON object is required.");return p as Json;}
async function auth(req:Request){const a=clean(req.headers.get("authorization"));if(!a.toLowerCase().startsWith("bearer "))throw new HttpError(401,"authentication_required","Sign in is required.");const h=await sha256(a.slice(7).trim());const{data:s}=await db.from("domain_sessions").select("*").eq("token_hash",h).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(!s)throw new HttpError(401,"invalid_session","Session expired or invalid.");const{data:u}=await db.from("domain_users").select("*").eq("id",s.user_id).maybeSingle();if(!u||u.status!=="active"||Number(u.session_version)!==Number(s.session_version))throw new HttpError(401,"invalid_session","Session expired or invalid.");return u as Json;}
async function config(){const{data,error}=await db.from("domain_config").select("support_email,payment_mode,wallet_topup_mode,maintenance_mode,customer_checkout_environment,registrar_environment").eq("id",true).single();if(error||!data)throw new HttpError(500,"config_missing","Domain configuration is missing.");return data as Json;}
function env(v:unknown):Environment{const x=clean(v).toLowerCase();return x==="production"?"production":"ote";}
async function summary(req:Request){const user=await auth(req),cfg=await config(),checkout=env(cfg.customer_checkout_environment||cfg.registrar_environment);const[credits,transactions,orders]=await Promise.all([db.from("domain_user_environment_balances").select("registrar_environment,balance_usd,updated_at").eq("user_id",user.id),db.from("domain_wallet_transactions").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50),db.from("domain_orders").select("id,order_number,type,domain_name,status,price_usd,amount_xaf,registrar_environment,created_at,domain_payments(id,provider,status,payment_method,registrar_environment,created_at)").eq("user_id",user.id).in("status",["pending_payment","payment_pending","paid","processing","failed"]).order("created_at",{ascending:false}).limit(50)]);const map:{ote:number;production:number}={ote:0,production:0};for(const row of credits.data||[])map[env(row.registrar_environment)]=money(row.balance_usd);const visibleOrders=(orders.data||[]).map(order=>({...order,payableInCurrentEnvironment:env(order.registrar_environment)===checkout}));return json(req,{customerCreditUsd:map[checkout],balanceUsd:map[checkout],balanceKind:"KmerHosting customer credit",notDomainNameApiBalance:true,checkoutEnvironment:checkout,testMode:checkout==="ote",credits:{ote:{customerCreditUsd:map.ote,label:"TEST / OTE customer credit"},production:{customerCreditUsd:map.production,label:"LIVE customer credit"}},providerBalanceNote:"DomainNameAPI reseller funds are checked separately from deposit/accounts/me usdBalance and are never represented by this customer credit.",transactions:transactions.data||[],orders:visibleOrders,topups:[],paymentMode:cfg.payment_mode||"wallet_only",topupMode:cfg.wallet_topup_mode||"manual_support",supportEmail:cfg.support_email||"support@kmerhosting.com",topupInstructions:`Contact ${cfg.support_email||"support@kmerhosting.com"} to request customer credit for the required TEST or LIVE environment.`});}
async function payOrder(req:Request){const user=await auth(req),payload=await body(req),orderId=clean(payload.orderId);if(!orderId)throw new HttpError(400,"order_required","Order ID is required.");const{data,error}=await db.rpc("domain_wallet_pay_order",{p_user_id:user.id,p_order_id:orderId});if(error){const m=String(error.message||"");if(m.includes("order_environment_mismatch"))throw new HttpError(409,"order_environment_mismatch","This order belongs to another registrar environment and cannot be paid while the current checkout environment is active.");if(m.includes("insufficient_wallet_balance"))throw new HttpError(402,"insufficient_customer_credit","Customer credit in this order environment is insufficient.");if(m.includes("order_not_found"))throw new HttpError(404,"order_not_found","Order not found.");if(m.includes("order_not_payable_from_wallet"))throw new HttpError(409,"order_not_payable","This order cannot be paid from customer credit.");throw error;}return json(req,{success:true,result:data,balanceKind:"KmerHosting customer credit"});}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});try{const path=pathOf(req);if(req.method==="GET"&&(path==="/"||path==="/health")){const cfg=await config(),checkout=env(cfg.customer_checkout_environment||cfg.registrar_environment);return json(req,{ok:true,service:"KmerHosting Customer Credit",version:3,checkoutEnvironment:checkout,testMode:checkout==="ote",balanceKind:"KmerHosting customer credit",providerBalanceSource:"DomainNameAPI deposit/accounts/me usdBalance",timestamp:new Date().toISOString()});}if(req.method==="GET"&&path==="/summary")return await summary(req);if(req.method==="POST"&&path==="/pay-order")return await payOrder(req);if(req.method==="POST"&&path==="/admin/credit")return json(req,{error:"explicit_environment_required",message:"Ambiguous credit endpoint disabled. Use the environment-specific customer-credit endpoint and choose ote or production."},410);if(path.startsWith("/topups")||path==="/poll")return json(req,{error:"manual_customer_credit_required",message:"Online top-ups are disabled. Customer credit is added manually and is separate from DomainNameAPI reseller funds."},410);return json(req,{error:"not_found",message:"Endpoint not found."},404);}catch(e){if(e instanceof HttpError)return json(req,{error:e.code,message:e.message,details:e.details},e.status);console.error(e);return json(req,{error:"internal_error",message:e instanceof Error?e.message:"Unexpected error."},500);}});
