import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const encoder = new TextEncoder();

type Json = Record<string, any>;
class HttpError extends Error { constructor(public status: number, public code: string, message: string, public details?: unknown) { super(message); } }
const clean = (v: unknown) => String(v ?? "").trim();
const now = () => new Date().toISOString();
function allowedOrigin(origin: string | null) { if (!origin) return "*"; try { const host = new URL(origin).hostname.toLowerCase(); if (host === "domain.kmerhosting.com" || host === "localhost" || host === "127.0.0.1" || host.endsWith(".vercel.app")) return origin; } catch {} return "https://domain.kmerhosting.com"; }
function cors(req: Request): HeadersInit { return { "Access-Control-Allow-Origin": allowedOrigin(req.headers.get("origin")), "Access-Control-Allow-Headers": "authorization, apikey, content-type", "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS", "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "Vary": "Origin", "X-Content-Type-Options": "nosniff" }; }
function json(req: Request, body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: cors(req) }); }
function pathOf(req: Request) { const p = new URL(req.url).pathname; const marker = "/domain-customer-tools"; const i = p.indexOf(marker); return (i >= 0 ? p.slice(i + marker.length) : p).replace(/\/+$/, "") || "/"; }
async function body(req: Request) { return await req.json().catch(() => ({})) as Json; }
async function sha256(value: string) { const d = new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value))); return Array.from(d).map((b) => b.toString(16).padStart(2, "0")).join(""); }
function pick(o: any, paths: string[]) { for (const path of paths) { let c = o; for (const k of path.split(".")) { if (!c || typeof c !== "object") { c = undefined; break; } c = c[k]; } if (c !== undefined && c !== null && clean(c) !== "") return c; } return undefined; }
function friendly(message: string, area = "domain") { const m = clean(message); if (/EPP integration|Your operation has failed|Unauthorized|internal error|Registrar request failed|registrar_error|429|403|timeout|Provider returned/i.test(m)) { if (area === "forwarding") return "Forwarding could not be updated for this domain right now."; if (area === "glue") return "The child nameserver could not be updated. Check the host name and IP address."; if (area === "contact_sync") return "The contact could not be synced right now. Check the contact details and try again."; if (area === "contact") return "The contact verification request could not be sent right now."; if (area === "restore") return "Restore could not be started. It is only available for eligible expired domains."; if (area === "auth") return "The transfer code is not available for this domain right now."; return "The domain update could not be completed right now."; } return m || "The operation could not be completed."; }
async function auth(req: Request) { const authorization = clean(req.headers.get("authorization")); if (!authorization.toLowerCase().startsWith("bearer ")) throw new HttpError(401, "authentication_required", "Authentication is required."); const tokenHash = await sha256(authorization.slice(7).trim()); const { data: session } = await db.from("domain_sessions").select("*").eq("token_hash", tokenHash).is("revoked_at", null).gt("expires_at", now()).maybeSingle(); if (!session) throw new HttpError(401, "invalid_session", "Session expired or invalid."); const { data: user } = await db.from("domain_users").select("*").eq("id", session.user_id).maybeSingle(); if (!user || user.status !== "active" || Number(user.session_version) !== Number(session.session_version)) throw new HttpError(401, "invalid_session", "Session expired or invalid."); return user as Json; }
async function getDomain(id: string, userId: string) { const { data, error } = await db.from("domain_domains").select("*").eq("id", id).eq("user_id", userId).maybeSingle(); if (error || !data) throw new HttpError(404, "domain_not_found", "Domain not found."); return data as Json; }
async function getContact(id: string, userId: string) { const { data, error } = await db.from("domain_contacts").select("*").eq("id", id).eq("user_id", userId).maybeSingle(); if (error || !data) throw new HttpError(404, "contact_not_found", "Contact not found."); return data as Json; }
async function registrar(path: string, method = "GET", bodyArg?: Json | null, query: Json = {}, area = "domain") { const { data, error } = await db.rpc("domain_registrar_proxy", { p_path: path, p_method: method, p_body: bodyArg ?? null, p_query: query }); if (error) throw new HttpError(504, "registrar_proxy_failed", friendly(error.message, area), error); const out = data as Json; if (!out || Number(out.status) >= 400) { const b = out?.body || {}; const msg = clean(pick(b, ["error.message", "message", "error", "title", "raw"])) || `Provider request failed (${out?.status || "unknown"}).`; throw new HttpError(Number(out?.status) >= 500 ? 502 : Number(out?.status || 502), "provider_error", friendly(msg, area), b); } return out.body as Json; }
async function notifyUser(userId: string, title: string, message: string, data: Json = {}) { const { error } = await db.from("domain_notifications").insert({ user_id: userId, type: "domain", title, message, data }); if (error) console.warn("notification_insert_failed", error.message); }
async function listNotifications(req: Request, user: Json) { const { data, error } = await db.from("domain_notifications").select("*").eq("user_id", user.id).order("created_at", { ascending: false }).limit(100); if (error) throw new HttpError(500, "notifications_load_failed", "Unable to load notifications.", error); const notifications = data || []; return json(req, { notifications, unread: notifications.filter((item: Json) => !item.read_at).length }); }
async function readNotification(req: Request, user: Json, notificationId: string) { const { data, error } = await db.from("domain_notifications").update({ read_at: now() }).eq("id", notificationId).eq("user_id", user.id).select("id,read_at").maybeSingle(); if (error) throw new HttpError(500, "notification_update_failed", "Unable to mark this notification as read.", error); if (!data) throw new HttpError(404, "notification_not_found", "Notification not found."); return json(req, { success: true, notification: data }); }
async function readAllNotifications(req: Request, user: Json) { const { data, error } = await db.from("domain_notifications").update({ read_at: now() }).eq("user_id", user.id).is("read_at", null).select("id"); if (error) throw new HttpError(500, "notifications_update_failed", "Unable to mark notifications as read.", error); return json(req, { success: true, updated: data?.length || 0 }); }
async function domainInfo(domainName: string) { try { return await registrar("/api/v1/domains/info", "POST", { domainName }, {}, "auth"); } catch (_first) { return await registrar("/api/v1/domains/info", "GET", null, { domainName }, "auth"); } }
function contactPayload(c: Json) { return { firstName: clean(c.first_name).slice(0, 80), lastName: clean(c.last_name).slice(0, 80), companyName: clean(c.company_name) || null, eMail: clean(c.email), phoneCountryCode: clean(c.phone_country_code).replace(/\D/g, "").slice(0, 3), phone: clean(c.phone).replace(/\D/g, "").slice(0, 16), faxCountryCode: clean(c.fax_country_code).replace(/\D/g, "").slice(0, 3) || null, fax: clean(c.fax).replace(/\D/g, "").slice(0, 15) || null, address: clean(c.address).slice(0, 256), city: clean(c.city).slice(0, 80), state: clean(c.state).slice(0, 80), postalCode: clean(c.postal_code).slice(0, 10), country: clean(c.country).toUpperCase().slice(0, 2) }; }
function extractHandle(provider: Json) { return clean(pick(provider, ["handleCode", "handle", "code", "contactHandle", "contactCode", "data.handleCode", "data.handle", "data.code", "data.contactHandle", "data.contactCode", "contact.handleCode", "contact.handle", "contact.code", "result.handleCode", "result.handle", "result.code"])); }
async function ensureProviderContact(contact: Json) { const existing = clean(contact.registrar_handle || contact.handle_code || contact.provider_handle); if (existing) return { handle: existing, synced: false, provider: contact.registrar_metadata || {} }; const provider = await registrar("/api/v1/contacts", "POST", contactPayload(contact), {}, "contact_sync"); const handle = extractHandle(provider); if (!handle) throw new HttpError(502, "provider_handle_missing", "The contact was created but the provider did not return a usable contact handle.", provider); const metadata = { ...(contact.registrar_metadata && typeof contact.registrar_metadata === "object" ? contact.registrar_metadata : {}), lastContactCreateResponse: provider }; const verified = Boolean(pick(provider, ["isEmailVerified", "verified", "data.isEmailVerified", "contact.isEmailVerified"]) || contact.registrar_verified); const { error } = await db.from("domain_contacts").update({ registrar_handle: handle, registrar_verified: verified, registrar_metadata: metadata, registrar_last_synced_at: now(), updated_at: now() }).eq("id", contact.id); if (error) throw new HttpError(500, "contact_sync_save_failed", "The contact was synced but could not be saved locally.", error); return { handle, synced: true, provider }; }
async function requestContactVerification(handle: string, contact: Json) { try { return await registrar("/api/v1/contacts/verification/request-token", "POST", { handleCode: handle }, {}, "contact"); } catch (first) { if (!(first instanceof HttpError) || first.status >= 500) throw first; return await registrar("/api/v1/contacts/verification/request-token", "POST", { email: contact.email, handle, handleCode: handle }, {}, "contact"); } }
async function transferCode(req: Request, user: Json, domainId: string, b: Json) { if (b.confirm !== true) throw new HttpError(400, "confirmation_required", "Confirm that you want to reveal the transfer code."); const domain = await getDomain(domainId, user.id); const info = await domainInfo(domain.domain_name); const authCode = clean(pick(info, ["authCode", "authorizationCode", "eppCode", "data.authCode", "data.authorizationCode", "data.eppCode", "info.authCode", "domain.authCode"])); if (!authCode) throw new HttpError(404, "transfer_code_unavailable", "The transfer code is not available for this domain right now."); await db.from("domain_audit_logs").insert({ user_id: user.id, action: "domain_transfer_code_viewed", entity_type: "domain", entity_id: domain.id, metadata: { domainName: domain.domain_name } }); await notifyUser(user.id, "Transfer code viewed", `The transfer code for ${domain.domain_name} was displayed.`, { domainId: domain.id }); return json(req, { domainName: domain.domain_name, transferCode: authCode, warning: "Keep this code private. Anyone with this code may be able to start a transfer." }); }
async function getForwarding(req: Request, user: Json, domainId: string) { const domain = await getDomain(domainId, user.id); const result = await registrar("/api/v1/domains/forwards", "GET", null, { domainName: domain.domain_name }, "forwarding"); return json(req, { domainName: domain.domain_name, forwarding: result }); }
async function setForwarding(req: Request, user: Json, domainId: string, b: Json) { const domain = await getDomain(domainId, user.id); const redirectAddress = clean(b.redirectAddress || b.url); if (!/^https?:\/\//i.test(redirectAddress)) throw new HttpError(400, "invalid_redirect_url", "Enter a redirect URL starting with http:// or https://."); const payload = { domainName: domain.domain_name, redirectAddress, forwardType: clean(b.forwardType) || "Permanent" }; const result = await registrar("/api/v1/domains/forwards", "POST", payload, {}, "forwarding"); await notifyUser(user.id, "Forwarding updated", `${domain.domain_name} forwarding was updated.`, { domainId: domain.id, redirectAddress }); return json(req, { success: true, domainName: domain.domain_name, forwarding: result }); }
async function deleteForwarding(req: Request, user: Json, domainId: string) { const domain = await getDomain(domainId, user.id); const result = await registrar("/api/v1/domains/forwards", "DELETE", null, { domainName: domain.domain_name }, "forwarding"); await notifyUser(user.id, "Forwarding removed", `${domain.domain_name} forwarding was removed.`, { domainId: domain.id }); return json(req, { success: true, domainName: domain.domain_name, forwarding: result }); }
async function restoreDomain(req: Request, user: Json, domainId: string, b: Json) { if (b.confirm !== true) throw new HttpError(400, "confirmation_required", "Confirm that you want to request a restore."); const domain = await getDomain(domainId, user.id); const result = await registrar("/api/v1/domains/restore", "POST", { domainName: domain.domain_name }, {}, "restore"); await db.from("domain_domains").update({ metadata: { ...(domain.metadata || {}), lastRestoreResponse: result }, last_synced_at: now(), updated_at: now() }).eq("id", domain.id); await notifyUser(user.id, "Restore requested", `${domain.domain_name} restore request was submitted.`, { domainId: domain.id }); return json(req, { success: true, domainName: domain.domain_name, restore: result }); }
async function createGlueHost(req: Request, user: Json, domainId: string, b: Json) { const domain = await getDomain(domainId, user.id); const hostName = clean(b.hostName).toLowerCase(); const ips = Array.isArray(b.ipAddresses) ? b.ipAddresses.map(clean).filter(Boolean) : [clean(b.ipAddress || b.ip)].filter(Boolean); if (!hostName || !ips.length) throw new HttpError(400, "invalid_glue_host", "Enter a host name and at least one IP address."); const payload = { domainName: domain.domain_name, hostName, ipAddresses: ips }; const result = await registrar("/api/v1/domains/dns/host", "POST", payload, {}, "glue"); await notifyUser(user.id, "Child nameserver created", `${hostName}.${domain.domain_name} was submitted.`, { domainId: domain.id, hostName, ipAddresses: ips }); return json(req, { success: true, domainName: domain.domain_name, host: result }); }
async function verifyContact(req: Request, user: Json, contactId: string) { const contact = await getContact(contactId, user.id); const synced = await ensureProviderContact(contact); const result = await requestContactVerification(synced.handle, contact); await db.from("domain_contacts").update({ registrar_metadata: { ...(contact.registrar_metadata && typeof contact.registrar_metadata === "object" ? contact.registrar_metadata : {}), lastVerificationRequestResponse: result }, registrar_last_synced_at: now(), updated_at: now() }).eq("id", contact.id); await notifyUser(user.id, "Contact verification sent", `A verification email was sent to ${contact.email}.`, { contactId: contact.id, synced: synced.synced }); return json(req, { success: true, contactId: contact.id, email: contact.email, syncedContact: synced.synced, handle: synced.handle, result }); }
Deno.serve(async (req) => { if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: cors(req) }); try { const path = pathOf(req); if (req.method === "GET" && (path === "/" || path === "/health")) return json(req, { ok: true, service: "KmerHosting Domain Customer Tools", version: 3, timestamp: now() }); const user = await auth(req); if (path === "/notifications" && req.method === "GET") return await listNotifications(req, user); if (path === "/notifications/read-all" && req.method === "POST") return await readAllNotifications(req, user); const notification = path.match(/^\/notifications\/([0-9a-f-]+)\/read$/i); if (notification && req.method === "POST") return await readNotification(req, user, notification[1]); const code = path.match(/^\/domains\/([0-9a-f-]+)\/transfer-code$/i); if (code && req.method === "POST") return await transferCode(req, user, code[1], await body(req)); const fwd = path.match(/^\/domains\/([0-9a-f-]+)\/forwarding$/i); if (fwd && req.method === "GET") return await getForwarding(req, user, fwd[1]); if (fwd && req.method === "PUT") return await setForwarding(req, user, fwd[1], await body(req)); if (fwd && req.method === "DELETE") return await deleteForwarding(req, user, fwd[1]); const restore = path.match(/^\/domains\/([0-9a-f-]+)\/restore$/i); if (restore && req.method === "POST") return await restoreDomain(req, user, restore[1], await body(req)); const glue = path.match(/^\/domains\/([0-9a-f-]+)\/glue-hosts$/i); if (glue && req.method === "POST") return await createGlueHost(req, user, glue[1], await body(req)); const contact = path.match(/^\/contacts\/([0-9a-f-]+)\/verification$/i); if (contact && req.method === "POST") return await verifyContact(req, user, contact[1]); return json(req, { error: "not_found", message: "Endpoint not found." }, 404); } catch (e) { if (e instanceof HttpError) return json(req, { error: e.code, message: e.message, details: e.details }, e.status); console.error(e); return json(req, { error: "internal_error", message: e instanceof Error ? e.message : "Unexpected error." }, 500); } });
