import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const encoder=new TextEncoder(),decoder=new TextDecoder();

type Json=Record<string,any>;
type Environment="ote"|"production";
class HttpError extends Error{constructor(public status:number,public code:string,message:string,public details?:unknown){super(message)}}
const clean=(v:unknown)=>String(v??"").trim();
const now=()=>new Date().toISOString();
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
function envOf(v:unknown):Environment{const x=clean(v).toLowerCase();if(x==="ote"||x==="production")return x;throw new HttpError(409,"registrar_environment_invalid","The registrar environment is invalid.")}
async function sha256(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(v)));return Array.from(d).map(b=>b.toString(16).padStart(2,"0")).join("")}
function fromB64(v:string){const n=v.replaceAll("-","+").replaceAll("_","/")+"=".repeat((4-v.length%4)%4);const b=atob(n);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function secret(name:string){const{data,error}=await db.rpc("domain_secret",{p_name:name});const value=clean(data);if(error||!value)throw new HttpError(503,"secret_missing",`${name} is not configured.`);return value}
async function decrypt(v:string|null|undefined){if(!v)return"";const[iv,cipher]=v.split(".");if(!iv||!cipher)throw new HttpError(500,"decrypt_failed","Sensitive order data is invalid.");const master=await secret("domain_data_encryption_key"),kb=new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(master))),key=await crypto.subtle.importKey("raw",kb,"AES-GCM",false,["decrypt"]),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64(iv)},key,fromB64(cipher));return decoder.decode(plain)}
async function authorize(req:Request){const supplied=clean(req.headers.get("x-domain-cron-secret")),expected=await secret("domain_internal_cron_secret");if(!supplied||await sha256(supplied)!==await sha256(expected))throw new HttpError(401,"invalid_automation_secret","Automation authorization failed.")}
async function assertNotMaintenance(){const{data,error}=await db.from("domain_config").select("maintenance_mode").eq("id",true).single();if(error||!data)throw new HttpError(500,"configuration_missing","Domain platform configuration is missing.");if(data.maintenance_mode)throw new HttpError(503,"maintenance_mode","Domain operations are temporarily paused.")}
function pick(o:any,paths:string[]){for(const path of paths){let c=o;for(const k of path.split(".")){if(!c||typeof c!=="object"){c=undefined;break}c=c[k]}if(c!==undefined&&c!==null&&clean(c)!=="")return c}return undefined}
function providerMessage(body:Json,status:number){return clean(pick(body,["error.message","error.details","message","operationMessage","reason","title","raw"]))||`Domain service request failed (${status}).`}
async function dna(environment:Environment,path:string,method="GET",body:Json|Json[]|null=null,query:Json={}){const{data,error}=await db.rpc("domain_registrar_proxy_env",{p_path:path,p_method:method,p_body:body,p_query:query,p_environment:environment});if(error)throw new HttpError(502,"provider_proxy_failed",error.message,error);const out=data as Json,status=Number(out?.status||0);if(!out||status>=400)throw new HttpError(status>=500?502:status||502,"provider_error",providerMessage(out?.body||{},status),out?.body||{});return out.body as Json}
function bool(v:unknown){return [true,1,"1","true","yes","available","active","success"].includes(v as any)}
function safeProvider(p:Json){const out={...p};delete out.authCode;delete out.authorizationCode;delete out.eppCode;if(Array.isArray(out.contacts))out.contacts=out.contacts.map((c:Json)=>({handle:c.handle||null,contactType:c.contactType||c.type||null,verified:c.isEmailVerified||c.verified||false}));return out}
function providerSuccess(p:Json){if(p?.success===false||p?.isSuccess===false||p?.error)return false;const s=clean(p?.status||p?.result||p?.operationResult||p?.data?.status).toLowerCase().replace(/[\s_-]+/g,"");return !s||["active","ok","success","successful","completed","true","pending","transferpending"].includes(s)}
function iso(v:unknown){if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()}
function infoFields(p:Json,existing:Json={}){const raw=clean(p.status||p.statusCode||p.domainStatus||p.data?.status||existing.status).toLowerCase();let status="active";if(/transfer/.test(raw))status="transfer_pending";else if(/redemption/.test(raw))status="redemption";else if(/pendingdelete/.test(raw))status="pending_delete";else if(/expire/.test(raw))status="expired";else if(/suspend|hold/.test(raw))status="suspended";else if(/fail|cancel/.test(raw))status=raw.replace(/[^a-z]+/g,"_")||"failed";const ns=pick(p,["nameservers","nameServers","data.nameservers","data.nameServers"]),eppRaw=clean(p.statusCode||p.eppStatus||p.data?.statusCode),epp=eppRaw?eppRaw.split(",").map(clean).filter(Boolean):Array.isArray(p.eppStatuses)?p.eppStatuses.map(clean):[];return{status,expires_at:iso(p.expirationDate||p.expiresAt||p.data?.expirationDate)||existing.expires_at||null,registered_at:iso(p.startDate||p.creationDate||p.registeredAt||p.data?.startDate)||existing.registered_at||null,nameservers:Array.isArray(ns)&&ns.length?ns.map(clean).filter(Boolean):existing.nameservers||[],registrar_domain_id:clean(p.objectId||p.domainId||p.id||p.data?.objectId)||existing.registrar_domain_id||null,locked:p.lockStatus!==undefined?Boolean(p.lockStatus):existing.locked??true,privacy_enabled:p.privacyProtectionStatus!==undefined?Boolean(p.privacyProtectionStatus):existing.privacy_enabled??false,epp_statuses:epp.length?epp:existing.epp_statuses||[],last_synced_at:now(),next_sync_at:new Date(Date.now()+(status==="transfer_pending"?3600_000:21600_000)).toISOString()}}
function contactDto(c:Json,contactType:string){return{contactType,firstName:clean(c.first_name).slice(0,80),lastName:clean(c.last_name).slice(0,80),companyName:clean(c.company_name).slice(0,256)||null,eMail:clean(c.email).slice(0,256),phoneCountryCode:clean(c.phone_country_code).replace(/\D/g,"").slice(0,3),phone:clean(c.phone).replace(/\D/g,"").slice(0,16),faxCountryCode:clean(c.fax_country_code).replace(/\D/g,"").slice(0,3)||null,fax:clean(c.fax).replace(/\D/g,"").slice(0,15)||null,address:clean(c.address).slice(0,256),city:clean(c.city).slice(0,80),state:clean(c.state).slice(0,80),postalCode:clean(c.postal_code).slice(0,10),country:clean(c.country).toUpperCase().slice(0,2),discloseFlag:false,isEmailVerified:Boolean(c.registrar_verified)}}
function contactRoles(c:Json){return[contactDto(c,"Registrant"),contactDto(c,"Admin"),contactDto(c,"Tech"),contactDto(c,"Billing")]}
async function providerBalance(environment:Environment,required:number){const p=await dna(environment,"/api/v1/deposit/accounts/me","GET",null,{currency:"USD"}),n=Number(p.usdBalance??p.data?.usdBalance);await db.from("domain_provider_balance_snapshots").insert({registrar_environment:environment,currency:"USD",balance:Number.isFinite(n)?n:null,provider_http_status:200,provider_payload:{usdBalance:Number.isFinite(n)?n:null,tryBalance:Number.isFinite(Number(p.tryBalance))?Number(p.tryBalance):null},status:Number.isFinite(n)?"success":"failed",error_message:Number.isFinite(n)?null:"USD balance unavailable"});if(!Number.isFinite(n)||n<required)throw new HttpError(409,"provider_balance_too_low",`${environment==="ote"?"TEST / OTE":"LIVE"} registrar balance is insufficient for this paid order.`,{requiredUsd:required,availableUsd:Number.isFinite(n)?n:null,registrarEnvironment:environment});return n}
async function fetchOrder(id:string){const{data:o,error}=await db.from("domain_orders").select("*").eq("id",id).single();if(error||!o)throw new HttpError(404,"order_not_found","Order not found.");const[{data:user},{data:contact},{data:domain},{data:quote}]=await Promise.all([db.from("domain_users").select("*").eq("id",o.user_id).maybeSingle(),o.contact_id?db.from("domain_contacts").select("*").eq("id",o.contact_id).maybeSingle():Promise.resolve({data:null} as any),o.domain_id?db.from("domain_domains").select("*").eq("id",o.domain_id).maybeSingle():Promise.resolve({data:null} as any),o.provider_quote_id?db.from("domain_provider_quotes").select("*").eq("id",o.provider_quote_id).maybeSingle():Promise.resolve({data:null} as any)]);return{order:o as Json,user:user as Json|null,contact:contact as Json|null,domain:domain as Json|null,quote:quote as Json|null}}
function assertJobEnvironment(job:Json,environment:Environment){if(envOf(job.registrar_environment)!==environment)throw new HttpError(409,"job_environment_mismatch","The job environment does not match its parent record.",{jobEnvironment:job.registrar_environment,parentEnvironment:environment})}
async function validatePaid(job:Json,ctx:{order:Json;quote:Json|null}){const o=ctx.order,q=ctx.quote,env=envOf(o.registrar_environment);assertJobEnvironment(job,env);if(o.status==="completed")return false;if(o.status!=="paid"||o.payment_method!=="wallet")throw new HttpError(409,"order_not_ready","Only paid wallet orders can be processed.");if(!q||q.id!==o.provider_quote_id||envOf(q.registrar_environment)!==env||!q.eligible)throw new HttpError(409,"provider_quote_invalid","The exact quote is missing or belongs to another environment.");if(Number(q.customer_price_usd)!==Number(o.price_usd)||Number(q.provider_cost_usd)!==Number(o.provider_required_cost_usd))throw new HttpError(409,"provider_quote_mismatch","The order price does not match its exact quote.");if(ctx.domain&&envOf(ctx.domain.registrar_environment)!==env)throw new HttpError(409,"domain_environment_mismatch","The order and domain environments differ.");return true}
async function markProcessing(o:Json,request:Json){await db.from("domain_orders").update({status:"processing",registrar_request:request,failure_code:null,failure_message:null,updated_at:now()}).eq("id",o.id)}
async function finish(o:Json,response:Json,domainId?:string|null){await db.from("domain_orders").update({status:"completed",completed_at:now(),domain_id:domainId||o.domain_id||null,registrar_response:safeProvider(response),registrar_order_id:clean(response.orderCode||response.orderId||response.id||response.data?.orderCode)||o.registrar_order_id||null,auth_code_ciphertext:null,failure_code:null,failure_message:null,updated_at:now()}).eq("id",o.id)}
async function assignRoles(domainId:string,userId:string,contactId:string){for(const role of["Registrant","Administrative","Technical","Billing"])await db.from("domain_contact_assignments").upsert({domain_id:domainId,user_id:userId,contact_id:contactId,contact_role:role,updated_at:now()},{onConflict:"domain_id,contact_role"})}
async function notify(user:Json|null,type:string,title:string,message:string,data:Json){if(user)await db.from("domain_notifications").insert({user_id:user.id,type,title,message,data})}
async function email(user:Json|null,o:Json,domainId:string|null,template:string,subject:string,payload:Json){if(user)await db.from("domain_email_outbox").upsert({event_key:`${template}:${o.id}`,user_id:user.id,order_id:o.id,domain_id:domainId,recipient_email:user.email,recipient_name:user.full_name,template,subject,payload},{onConflict:"event_key",ignoreDuplicates:true})}
async function syncInfo(domain:Json,job?:Json){const env=envOf(domain.registrar_environment);if(job)assertJobEnvironment(job,env);let info=await dna(env,"/api/v1/domains/info","GET",null,{DomainName:domain.domain_name});if(domain.status==="transfer_pending"){try{const transfer=await dna(env,"/api/v1/domains/transfers/query","POST",{domainName:domain.domain_name});info={...info,transferQuery:safeProvider(transfer)}}catch{}}const fields=infoFields(info,domain);await db.from("domain_domains").update({...fields,metadata:{...(domain.metadata||{}),lastProviderInfo:safeProvider(info)},updated_at:now()}).eq("id",domain.id);return{...domain,...fields}}
async function saveDomain(values:Json){const env=envOf(values.registrar_environment);const{data,error}=await db.from("domain_domains").upsert({...values,registrar_environment:env,updated_at:now()},{onConflict:"domain_name,registrar_environment"}).select("*").single();if(error||!data)throw error||new Error("domain_upsert_failed");return data as Json}
async function processRegister(job:Json){const ctx=await fetchOrder(job.order_id);if(!await validatePaid(job,ctx))return{skipped:true};if(!ctx.contact)throw new HttpError(400,"contact_missing","Registration contact is missing.");const env=envOf(ctx.order.registrar_environment);await providerBalance(env,Number(ctx.quote!.provider_cost_usd));const request={domainName:ctx.order.domain_name,period:Number(ctx.order.years),nameServers:ctx.order.nameservers||[],isLocked:Boolean(ctx.order.lock_requested),privacyEnabled:Boolean(ctx.order.privacy_requested),contacts:contactRoles(ctx.contact),tldAttributes:ctx.order.tld_attributes||{}};await markProcessing(ctx.order,request);const response=await dna(env,"/api/v1/domains/register-with-contacts","POST",request);if(!providerSuccess(response))throw new HttpError(502,"registration_failed","The registrar did not confirm registration.",response);let info:Json=response;try{info=await dna(env,"/api/v1/domains/info","GET",null,{DomainName:ctx.order.domain_name})}catch{}const fields=infoFields(info,{nameservers:ctx.order.nameservers,locked:ctx.order.lock_requested,privacy_enabled:ctx.order.privacy_requested}),domain=await saveDomain({user_id:ctx.order.user_id,contact_id:ctx.order.contact_id,domain_name:ctx.order.domain_name,tld:ctx.order.tld,registrar_environment:env,registrar_order_id:clean(response.orderCode||response.orderId||response.id)||null,...fields,auto_renew:true,metadata:{registrationResponse:safeProvider(response),lastProviderInfo:safeProvider(info),registrarEnvironment:env,testMode:env==="ote"}});await assignRoles(domain.id,ctx.order.user_id,ctx.contact.id);await finish(ctx.order,response,domain.id);const prefix=env==="ote"?"[TEST] ":"";await notify(ctx.user,"domain_ready",`${prefix}Domain ready`,`${prefix}${ctx.order.domain_name} is active.`,{domainId:domain.id,orderId:ctx.order.id,registrarEnvironment:env,testMode:env==="ote"});await email(ctx.user,ctx.order,domain.id,"domain_ready",`${prefix}${ctx.order.domain_name} is ready`,{name:ctx.user?.full_name,domainName:ctx.order.domain_name,orderNumber:ctx.order.order_number,expiresAt:fields.expires_at,registrarEnvironment:env,testMode:env==="ote"});return{domainId:domain.id,registrarEnvironment:env,testMode:env==="ote"}}
async function processTransfer(job:Json){const ctx=await fetchOrder(job.order_id);if(!await validatePaid(job,ctx))return{skipped:true};if(!ctx.contact)throw new HttpError(400,"contact_missing","Transfer contact is missing.");const env=envOf(ctx.order.registrar_environment),code=await decrypt(ctx.order.auth_code_ciphertext);if(code.length<4)throw new HttpError(400,"auth_code_missing","Transfer authorization code is missing.");await providerBalance(env,Number(ctx.quote!.provider_cost_usd));const check=await dna(env,"/api/v1/domains/transfers/check","POST",{domainName:ctx.order.domain_name,authCode:code}),transferable=bool(check.transferAvailabilityStatus??check.data?.transferAvailabilityStatus);if(!transferable)throw new HttpError(409,"transfer_not_available",clean(check.message||check.data?.message)||"The transfer is no longer available.",check);const request={domainName:ctx.order.domain_name,period:Number(ctx.order.years),authCode:code,contacts:contactRoles(ctx.contact)};await markProcessing(ctx.order,{...request,authCode:"[encrypted]"});const response=await dna(env,"/api/v1/domains/transfer","POST",request);if(!providerSuccess(response))throw new HttpError(502,"transfer_failed","The registrar did not accept the transfer.",response);const domain=await saveDomain({user_id:ctx.order.user_id,contact_id:ctx.order.contact_id,domain_name:ctx.order.domain_name,tld:ctx.order.tld,registrar_environment:env,registrar_order_id:clean(response.orderCode||response.orderId||response.id)||null,status:"transfer_pending",auto_renew:true,privacy_enabled:false,locked:true,nameservers:ctx.order.nameservers||[],metadata:{transferResponse:safeProvider(response),transferCheck:safeProvider(check),registrarEnvironment:env,testMode:env==="ote"},last_synced_at:now(),next_sync_at:new Date(Date.now()+3600_000).toISOString()});await assignRoles(domain.id,ctx.order.user_id,ctx.contact.id);await finish(ctx.order,response,domain.id);const prefix=env==="ote"?"[TEST] ":"";await notify(ctx.user,"transfer_started",`${prefix}Transfer started`,`${prefix}Transfer request for ${ctx.order.domain_name} was submitted.`,{domainId:domain.id,orderId:ctx.order.id,registrarEnvironment:env,testMode:env==="ote"});return{domainId:domain.id,registrarEnvironment:env,testMode:env==="ote"}}
async function processRenew(job:Json){const ctx=await fetchOrder(job.order_id);if(!await validatePaid(job,ctx))return{skipped:true};if(!ctx.domain)throw new HttpError(404,"domain_not_found","Renewal domain not found.");const env=envOf(ctx.order.registrar_environment);await providerBalance(env,Number(ctx.quote!.provider_cost_usd));const request={domainName:ctx.order.domain_name,period:Number(ctx.order.years)};await dna(env,"/api/v1/domains/renew/check","POST",request);await markProcessing(ctx.order,request);const response=await dna(env,"/api/v1/domains/renew","POST",request);if(!providerSuccess(response))throw new HttpError(502,"renewal_failed","The registrar did not confirm renewal.",response);let updated=ctx.domain;try{updated=await syncInfo(ctx.domain,job)}catch{const base=ctx.domain.expires_at&&new Date(ctx.domain.expires_at).getTime()>Date.now()?new Date(ctx.domain.expires_at):new Date();base.setUTCFullYear(base.getUTCFullYear()+Number(ctx.order.years));await db.from("domain_domains").update({status:"active",expires_at:base.toISOString(),last_reminder_days:null,metadata:{...(ctx.domain.metadata||{}),renewalResponse:safeProvider(response)},updated_at:now()}).eq("id",ctx.domain.id);updated={...ctx.domain,status:"active",expires_at:base.toISOString()}}await finish(ctx.order,response,ctx.domain.id);const prefix=env==="ote"?"[TEST] ":"";await notify(ctx.user,"renewal_completed",`${prefix}Renewal completed`,`${prefix}${ctx.order.domain_name} was renewed.`,{domainId:ctx.domain.id,orderId:ctx.order.id,registrarEnvironment:env,testMode:env==="ote"});return{domainId:ctx.domain.id,expiresAt:updated.expires_at,registrarEnvironment:env,testMode:env==="ote"}}
async function processRestore(job:Json){const ctx=await fetchOrder(job.order_id);if(!await validatePaid(job,ctx))return{skipped:true};if(!ctx.domain)throw new HttpError(404,"domain_not_found","Restore domain not found.");const env=envOf(ctx.order.registrar_environment);await providerBalance(env,Number(ctx.quote!.provider_cost_usd));const request={domainName:ctx.order.domain_name};await markProcessing(ctx.order,request);const response=await dna(env,"/api/v1/domains/restore","POST",request);if(!providerSuccess(response))throw new HttpError(502,"restore_failed","The registrar did not accept the restore request.",response);await db.from("domain_domains").update({status:"restoring",metadata:{...(ctx.domain.metadata||{}),restoreResponse:safeProvider(response)},next_sync_at:new Date(Date.now()+3600_000).toISOString(),updated_at:now()}).eq("id",ctx.domain.id);await finish(ctx.order,response,ctx.domain.id);return{domainId:ctx.domain.id,registrarEnvironment:env,testMode:env==="ote"}}
async function processSync(job:Json){const{data:domain}=await db.from("domain_domains").select("*").eq("id",job.domain_id).maybeSingle();if(!domain)return{skipped:true};return await syncInfo(domain as Json,job)}
async function processNameservers(job:Json){const{data:domain}=await db.from("domain_domains").select("*").eq("id",job.domain_id).maybeSingle();if(!domain)throw new HttpError(404,"domain_not_found","Domain not found.");const env=envOf(domain.registrar_environment);assertJobEnvironment(job,env);const ns=Array.isArray(job.payload?.nameServers)?[...new Set(job.payload.nameServers.map(clean).filter(Boolean))]:[];if(ns.length<2||ns.length>13)throw new HttpError(400,"invalid_nameservers","Provide between 2 and 13 nameservers.");const response=await dna(env,"/api/v1/domains/dns/name-server","PUT",{domainName:domain.domain_name,nameServers:ns});await db.from("domain_domains").update({nameservers:ns,metadata:{...(domain.metadata||{}),nameserverResponse:safeProvider(response)},last_synced_at:now(),updated_at:now()}).eq("id",domain.id);return{domainId:domain.id,nameservers:ns,registrarEnvironment:env,testMode:env==="ote"}}
async function processJob(job:Json){if(job.type==="register_domain")return processRegister(job);if(job.type==="transfer_domain")return processTransfer(job);if(job.type==="renew_domain")return processRenew(job);if(job.type==="restore_domain")return processRestore(job);if(job.type==="sync_domain")return processSync(job);if(job.type==="update_nameservers")return processNameservers(job);throw new HttpError(400,"unknown_job",`Unknown domain job type: ${job.type}`)}
async function run(limit=20){await assertNotMaintenance();const worker=`domain-jobs-v4-${crypto.randomUUID()}`,{data:jobs,error}=await db.rpc("domain_claim_jobs",{p_worker:worker,p_limit:limit});if(error)throw error;let completed=0,failed=0,dead=0;const environments:{ote:number;production:number}={ote:0,production:0};for(const job of jobs||[]){try{const env=envOf(job.registrar_environment);environments[env]++;const result=await processJob(job);await db.from("domain_jobs").update({status:"completed",completed_at:now(),locked_at:null,locked_by:null,last_error:null,payload:{...(job.payload||{}),result}}).eq("id",job.id);completed++}catch(e){const msg=e instanceof Error?e.message:clean(e)||"Unknown error",isDead=Number(job.attempts)>=Number(job.max_attempts),delay=Math.min(360,2**Math.max(0,Number(job.attempts)-1));await db.from("domain_jobs").update({status:isDead?"dead":"failed",run_after:new Date(Date.now()+delay*60_000).toISOString(),locked_at:null,locked_by:null,last_error:msg.slice(0,2000)}).eq("id",job.id);if(job.order_id&&isDead){await db.from("domain_orders").update({status:"failed",failure_code:e instanceof HttpError?e.code:"provider_operation_failed",failure_message:msg,updated_at:now()}).eq("id",job.order_id);await db.rpc("domain_refund_order_to_wallet",{p_order_id:job.order_id,p_reason:msg});dead++}failed++}}return{claimed:jobs?.length||0,completed,failed,dead,environments}}
Deno.serve(async req=>{try{if(req.method==="GET")return json({ok:true,service:"KmerHosting Domain Jobs",version:4,environmentIsolation:true,timestamp:now()});if(req.method!=="POST")throw new HttpError(405,"method_not_allowed","Use POST.");await authorize(req);const body=await req.json().catch(()=>({})) as Json;return json({success:true,result:await run(Math.max(1,Math.min(50,Number(body.limit||20)))),at:now()})}catch(e){if(e instanceof HttpError)return json({error:e.code,message:e.message,details:e.details},e.status);console.error(e);return json({error:"internal_error",message:e instanceof Error?e.message:"Unexpected error."},500)}});
