import { COMMON_MESSAGES, normalizeLocale, type KmerLocale } from "@kmerhosting/i18n";
import { useEffect, useState } from "react";

export type DomainShellMessages = {
  overview: string; domains: string; orders: string; contacts: string; invoices: string; profile: string;
  search: string; pricing: string; allTlds: string; features: string; sharedHosting: string; transfer: string;
  notifications: string; account: string; accountMenu: string; connectedServices: string; customerDashboard: string;
  centralAccount: string; signOut: string; domainAccount: string; sessionActive: string; centralAccess: string;
  closeNavigation: string; openNavigation: string; useLightTheme: string; useDarkTheme: string; navigation: string;
};

const messages: Record<KmerLocale, DomainShellMessages> = {
  en: { overview: "Overview", domains: "Domains", orders: "Orders", contacts: "Contacts", invoices: "Invoices", profile: "Profile", search: "Search", pricing: "Pricing", allTlds: "All TLDs", features: "Features", sharedHosting: "Shared Hosting", transfer: "Transfer", notifications: "Notifications", account: "Account", accountMenu: "Account menu", connectedServices: "Connected services", customerDashboard: "Customer Dashboard", centralAccount: "Central account", signOut: "Sign out", domainAccount: "Domain account", sessionActive: "Your domain service session is active.", centralAccess: "Use your central account to access domain services.", closeNavigation: "Close navigation", openNavigation: "Open navigation", useLightTheme: "Use light theme", useDarkTheme: "Use dark theme", navigation: "KmerHosting Domains navigation" },
  fr: { overview: "Vue d’ensemble", domains: "Domaines", orders: "Commandes", contacts: "Contacts", invoices: "Factures", profile: "Profil", search: "Rechercher", pricing: "Tarifs", allTlds: "Tous les TLD", features: "Fonctionnalités", sharedHosting: "Hébergement mutualisé", transfer: "Transférer", notifications: "Notifications", account: "Compte", accountMenu: "Menu du compte", connectedServices: "Services connectés", customerDashboard: "Tableau de bord client", centralAccount: "Compte central", signOut: "Se déconnecter", domainAccount: "Compte domaines", sessionActive: "Votre session du service de domaines est active.", centralAccess: "Utilisez votre compte central pour accéder aux services de domaines.", closeNavigation: "Fermer la navigation", openNavigation: "Ouvrir la navigation", useLightTheme: "Utiliser le thème clair", useDarkTheme: "Utiliser le thème sombre", navigation: "Navigation KmerHosting Domaines" },
  es: { overview: "Resumen", domains: "Dominios", orders: "Pedidos", contacts: "Contactos", invoices: "Facturas", profile: "Perfil", search: "Buscar", pricing: "Precios", allTlds: "Todos los TLD", features: "Funciones", sharedHosting: "Hosting compartido", transfer: "Transferir", notifications: "Notificaciones", account: "Cuenta", accountMenu: "Menú de cuenta", connectedServices: "Servicios conectados", customerDashboard: "Panel del cliente", centralAccount: "Cuenta central", signOut: "Cerrar sesión", domainAccount: "Cuenta de dominios", sessionActive: "Tu sesión del servicio de dominios está activa.", centralAccess: "Usa tu cuenta central para acceder a los servicios de dominios.", closeNavigation: "Cerrar navegación", openNavigation: "Abrir navegación", useLightTheme: "Usar tema claro", useDarkTheme: "Usar tema oscuro", navigation: "Navegación de KmerHosting Dominios" },
  pt: { overview: "Visão geral", domains: "Domínios", orders: "Pedidos", contacts: "Contactos", invoices: "Faturas", profile: "Perfil", search: "Pesquisar", pricing: "Preços", allTlds: "Todos os TLD", features: "Funcionalidades", sharedHosting: "Alojamento partilhado", transfer: "Transferir", notifications: "Notificações", account: "Conta", accountMenu: "Menu da conta", connectedServices: "Serviços ligados", customerDashboard: "Painel do cliente", centralAccount: "Conta central", signOut: "Terminar sessão", domainAccount: "Conta de domínios", sessionActive: "A sua sessão do serviço de domínios está ativa.", centralAccess: "Use a sua conta central para aceder aos serviços de domínios.", closeNavigation: "Fechar navegação", openNavigation: "Abrir navegação", useLightTheme: "Usar tema claro", useDarkTheme: "Usar tema escuro", navigation: "Navegação de Domínios KmerHosting" },
  de: { overview: "Übersicht", domains: "Domains", orders: "Bestellungen", contacts: "Kontakte", invoices: "Rechnungen", profile: "Profil", search: "Suchen", pricing: "Preise", allTlds: "Alle TLDs", features: "Funktionen", sharedHosting: "Shared Hosting", transfer: "Transfer", notifications: "Benachrichtigungen", account: "Konto", accountMenu: "Kontomenü", connectedServices: "Verbundene Dienste", customerDashboard: "Kunden-Dashboard", centralAccount: "Zentrales Konto", signOut: "Abmelden", domainAccount: "Domain-Konto", sessionActive: "Ihre Domain-Service-Sitzung ist aktiv.", centralAccess: "Verwenden Sie Ihr zentrales Konto, um auf Domain-Dienste zuzugreifen.", closeNavigation: "Navigation schließen", openNavigation: "Navigation öffnen", useLightTheme: "Helles Design verwenden", useDarkTheme: "Dunkles Design verwenden", navigation: "KmerHosting Domains-Navigation" },
  "zh-Hans": { overview: "概览", domains: "域名", orders: "订单", contacts: "联系人", invoices: "发票", profile: "个人资料", search: "搜索", pricing: "价格", allTlds: "所有 TLD", features: "功能", sharedHosting: "共享主机", transfer: "转移", notifications: "通知", account: "账户", accountMenu: "账户菜单", connectedServices: "已连接服务", customerDashboard: "客户控制面板", centralAccount: "中央账户", signOut: "退出登录", domainAccount: "域名账户", sessionActive: "您的域名服务会话处于活动状态。", centralAccess: "使用您的中央账户访问域名服务。", closeNavigation: "关闭导航", openNavigation: "打开导航", useLightTheme: "使用浅色主题", useDarkTheme: "使用深色主题", navigation: "KmerHosting 域名导航" },
  ar: { overview: "نظرة عامة", domains: "النطاقات", orders: "الطلبات", contacts: "جهات الاتصال", invoices: "الفواتير", profile: "الملف الشخصي", search: "بحث", pricing: "الأسعار", allTlds: "جميع نطاقات TLD", features: "الميزات", sharedHosting: "الاستضافة المشتركة", transfer: "نقل", notifications: "الإشعارات", account: "الحساب", accountMenu: "قائمة الحساب", connectedServices: "الخدمات المتصلة", customerDashboard: "لوحة تحكم العميل", centralAccount: "الحساب المركزي", signOut: "تسجيل الخروج", domainAccount: "حساب النطاقات", sessionActive: "جلسة خدمة النطاقات الخاصة بك نشطة.", centralAccess: "استخدم حسابك المركزي للوصول إلى خدمات النطاقات.", closeNavigation: "إغلاق التنقل", openNavigation: "فتح التنقل", useLightTheme: "استخدام السمة الفاتحة", useDarkTheme: "استخدام السمة الداكنة", navigation: "تنقل نطاقات KmerHosting" },
  hi: { overview: "अवलोकन", domains: "डोमेन", orders: "ऑर्डर", contacts: "संपर्क", invoices: "चालान", profile: "प्रोफ़ाइल", search: "खोजें", pricing: "मूल्य", allTlds: "सभी TLD", features: "सुविधाएँ", sharedHosting: "शेयर्ड होस्टिंग", transfer: "ट्रांसफ़र", notifications: "सूचनाएँ", account: "खाता", accountMenu: "खाता मेनू", connectedServices: "कनेक्टेड सेवाएँ", customerDashboard: "ग्राहक डैशबोर्ड", centralAccount: "केंद्रीय खाता", signOut: "साइन आउट", domainAccount: "डोमेन खाता", sessionActive: "आपका डोमेन सेवा सत्र सक्रिय है।", centralAccess: "डोमेन सेवाओं तक पहुँचने के लिए अपने केंद्रीय खाते का उपयोग करें।", closeNavigation: "नेविगेशन बंद करें", openNavigation: "नेविगेशन खोलें", useLightTheme: "हल्की थीम उपयोग करें", useDarkTheme: "गहरी थीम उपयोग करें", navigation: "KmerHosting डोमेन नेविगेशन" },
  bn: { overview: "ওভারভিউ", domains: "ডোমেইন", orders: "অর্ডার", contacts: "যোগাযোগ", invoices: "ইনভয়েস", profile: "প্রোফাইল", search: "অনুসন্ধান", pricing: "মূল্য", allTlds: "সব TLD", features: "ফিচার", sharedHosting: "শেয়ার্ড হোস্টিং", transfer: "ট্রান্সফার", notifications: "নোটিফিকেশন", account: "অ্যাকাউন্ট", accountMenu: "অ্যাকাউন্ট মেনু", connectedServices: "সংযুক্ত সেবা", customerDashboard: "গ্রাহক ড্যাশবোর্ড", centralAccount: "কেন্দ্রীয় অ্যাকাউন্ট", signOut: "সাইন আউট", domainAccount: "ডোমেইন অ্যাকাউন্ট", sessionActive: "আপনার ডোমেইন সেবা সেশন সক্রিয়।", centralAccess: "ডোমেইন সেবায় প্রবেশ করতে আপনার কেন্দ্রীয় অ্যাকাউন্ট ব্যবহার করুন।", closeNavigation: "নেভিগেশন বন্ধ করুন", openNavigation: "নেভিগেশন খুলুন", useLightTheme: "হালকা থিম ব্যবহার করুন", useDarkTheme: "গাঢ় থিম ব্যবহার করুন", navigation: "KmerHosting ডোমেইন নেভিগেশন" },
  id: { overview: "Ringkasan", domains: "Domain", orders: "Pesanan", contacts: "Kontak", invoices: "Faktur", profile: "Profil", search: "Cari", pricing: "Harga", allTlds: "Semua TLD", features: "Fitur", sharedHosting: "Hosting bersama", transfer: "Transfer", notifications: "Notifikasi", account: "Akun", accountMenu: "Menu akun", connectedServices: "Layanan terhubung", customerDashboard: "Dasbor pelanggan", centralAccount: "Akun pusat", signOut: "Keluar", domainAccount: "Akun domain", sessionActive: "Sesi layanan domain Anda aktif.", centralAccess: "Gunakan akun pusat Anda untuk mengakses layanan domain.", closeNavigation: "Tutup navigasi", openNavigation: "Buka navigasi", useLightTheme: "Gunakan tema terang", useDarkTheme: "Gunakan tema gelap", navigation: "Navigasi Domain KmerHosting" },
  ja: { overview: "概要", domains: "ドメイン", orders: "注文", contacts: "連絡先", invoices: "請求書", profile: "プロフィール", search: "検索", pricing: "料金", allTlds: "すべての TLD", features: "機能", sharedHosting: "共有ホスティング", transfer: "移管", notifications: "通知", account: "アカウント", accountMenu: "アカウントメニュー", connectedServices: "接続済みサービス", customerDashboard: "顧客ダッシュボード", centralAccount: "中央アカウント", signOut: "サインアウト", domainAccount: "ドメインアカウント", sessionActive: "ドメインサービスのセッションは有効です。", centralAccess: "中央アカウントを使用してドメインサービスにアクセスします。", closeNavigation: "ナビゲーションを閉じる", openNavigation: "ナビゲーションを開く", useLightTheme: "ライトテーマを使用", useDarkTheme: "ダークテーマを使用", navigation: "KmerHosting ドメインナビゲーション" },
  ru: { overview: "Обзор", domains: "Домены", orders: "Заказы", contacts: "Контакты", invoices: "Счета", profile: "Профиль", search: "Поиск", pricing: "Цены", allTlds: "Все TLD", features: "Возможности", sharedHosting: "Shared Hosting", transfer: "Перенос", notifications: "Уведомления", account: "Аккаунт", accountMenu: "Меню аккаунта", connectedServices: "Подключённые сервисы", customerDashboard: "Панель клиента", centralAccount: "Центральный аккаунт", signOut: "Выйти", domainAccount: "Аккаунт доменов", sessionActive: "Сессия сервиса доменов активна.", centralAccess: "Используйте центральный аккаунт для доступа к сервисам доменов.", closeNavigation: "Закрыть навигацию", openNavigation: "Открыть навигацию", useLightTheme: "Использовать светлую тему", useDarkTheme: "Использовать тёмную тему", navigation: "Навигация доменов KmerHosting" },
  it: { overview: "Panoramica", domains: "Domini", orders: "Ordini", contacts: "Contatti", invoices: "Fatture", profile: "Profilo", search: "Cerca", pricing: "Prezzi", allTlds: "Tutti i TLD", features: "Funzionalità", sharedHosting: "Hosting condiviso", transfer: "Trasferisci", notifications: "Notifiche", account: "Account", accountMenu: "Menu account", connectedServices: "Servizi collegati", customerDashboard: "Dashboard cliente", centralAccount: "Account centrale", signOut: "Esci", domainAccount: "Account domini", sessionActive: "La sessione del servizio domini è attiva.", centralAccess: "Usa il tuo account centrale per accedere ai servizi di dominio.", closeNavigation: "Chiudi navigazione", openNavigation: "Apri navigazione", useLightTheme: "Usa tema chiaro", useDarkTheme: "Usa tema scuro", navigation: "Navigazione Domini KmerHosting" },
  ko: { overview: "개요", domains: "도메인", orders: "주문", contacts: "연락처", invoices: "청구서", profile: "프로필", search: "검색", pricing: "요금", allTlds: "모든 TLD", features: "기능", sharedHosting: "공유 호스팅", transfer: "이전", notifications: "알림", account: "계정", accountMenu: "계정 메뉴", connectedServices: "연결된 서비스", customerDashboard: "고객 대시보드", centralAccount: "중앙 계정", signOut: "로그아웃", domainAccount: "도메인 계정", sessionActive: "도메인 서비스 세션이 활성 상태입니다.", centralAccess: "중앙 계정을 사용하여 도메인 서비스에 액세스하세요.", closeNavigation: "탐색 닫기", openNavigation: "탐색 열기", useLightTheme: "라이트 테마 사용", useDarkTheme: "다크 테마 사용", navigation: "KmerHosting 도메인 탐색" },
  tr: { overview: "Genel bakış", domains: "Alan adları", orders: "Siparişler", contacts: "Kişiler", invoices: "Faturalar", profile: "Profil", search: "Ara", pricing: "Fiyatlandırma", allTlds: "Tüm TLD'ler", features: "Özellikler", sharedHosting: "Paylaşımlı hosting", transfer: "Transfer", notifications: "Bildirimler", account: "Hesap", accountMenu: "Hesap menüsü", connectedServices: "Bağlı hizmetler", customerDashboard: "Müşteri paneli", centralAccount: "Merkezi hesap", signOut: "Çıkış yap", domainAccount: "Alan adı hesabı", sessionActive: "Alan adı hizmeti oturumunuz etkin.", centralAccess: "Alan adı hizmetlerine erişmek için merkezi hesabınızı kullanın.", closeNavigation: "Gezinmeyi kapat", openNavigation: "Gezinmeyi aç", useLightTheme: "Açık temayı kullan", useDarkTheme: "Koyu temayı kullan", navigation: "KmerHosting Alan Adları navigasyonu" },
  vi: { overview: "Tổng quan", domains: "Tên miền", orders: "Đơn hàng", contacts: "Liên hệ", invoices: "Hóa đơn", profile: "Hồ sơ", search: "Tìm kiếm", pricing: "Bảng giá", allTlds: "Tất cả TLD", features: "Tính năng", sharedHosting: "Hosting chia sẻ", transfer: "Chuyển", notifications: "Thông báo", account: "Tài khoản", accountMenu: "Menu tài khoản", connectedServices: "Dịch vụ đã kết nối", customerDashboard: "Bảng điều khiển khách hàng", centralAccount: "Tài khoản trung tâm", signOut: "Đăng xuất", domainAccount: "Tài khoản tên miền", sessionActive: "Phiên dịch vụ tên miền của bạn đang hoạt động.", centralAccess: "Dùng tài khoản trung tâm để truy cập dịch vụ tên miền.", closeNavigation: "Đóng điều hướng", openNavigation: "Mở điều hướng", useLightTheme: "Dùng giao diện sáng", useDarkTheme: "Dùng giao diện tối", navigation: "Điều hướng Tên miền KmerHosting" },
  ur: { overview: "جائزہ", domains: "ڈومین", orders: "آرڈرز", contacts: "رابطے", invoices: "انوائسز", profile: "پروفائل", search: "تلاش", pricing: "قیمتیں", allTlds: "تمام TLD", features: "خصوصیات", sharedHosting: "شیئرڈ ہوسٹنگ", transfer: "منتقلی", notifications: "اطلاعات", account: "اکاؤنٹ", accountMenu: "اکاؤنٹ مینو", connectedServices: "منسلک خدمات", customerDashboard: "کسٹمر ڈیش بورڈ", centralAccount: "مرکزی اکاؤنٹ", signOut: "سائن آؤٹ", domainAccount: "ڈومین اکاؤنٹ", sessionActive: "آپ کا ڈومین سروس سیشن فعال ہے۔", centralAccess: "ڈومین خدمات تک رسائی کے لیے اپنا مرکزی اکاؤنٹ استعمال کریں۔", closeNavigation: "نیویگیشن بند کریں", openNavigation: "نیویگیشن کھولیں", useLightTheme: "ہلکی تھیم استعمال کریں", useDarkTheme: "گہری تھیم استعمال کریں", navigation: "KmerHosting ڈومین نیویگیشن" },
  nl: { overview: "Overzicht", domains: "Domeinen", orders: "Bestellingen", contacts: "Contacten", invoices: "Facturen", profile: "Profiel", search: "Zoeken", pricing: "Prijzen", allTlds: "Alle TLD's", features: "Functies", sharedHosting: "Shared hosting", transfer: "Verhuizen", notifications: "Meldingen", account: "Account", accountMenu: "Accountmenu", connectedServices: "Verbonden diensten", customerDashboard: "Klantdashboard", centralAccount: "Centraal account", signOut: "Uitloggen", domainAccount: "Domeinaccount", sessionActive: "Uw domeinservicesessie is actief.", centralAccess: "Gebruik uw centrale account om domeindiensten te openen.", closeNavigation: "Navigatie sluiten", openNavigation: "Navigatie openen", useLightTheme: "Licht thema gebruiken", useDarkTheme: "Donker thema gebruiken", navigation: "KmerHosting Domeinen-navigatie" },
  pl: { overview: "Przegląd", domains: "Domeny", orders: "Zamówienia", contacts: "Kontakty", invoices: "Faktury", profile: "Profil", search: "Szukaj", pricing: "Cennik", allTlds: "Wszystkie TLD", features: "Funkcje", sharedHosting: "Hosting współdzielony", transfer: "Transfer", notifications: "Powiadomienia", account: "Konto", accountMenu: "Menu konta", connectedServices: "Połączone usługi", customerDashboard: "Panel klienta", centralAccount: "Konto centralne", signOut: "Wyloguj się", domainAccount: "Konto domen", sessionActive: "Sesja usługi domen jest aktywna.", centralAccess: "Użyj konta centralnego, aby uzyskać dostęp do usług domen.", closeNavigation: "Zamknij nawigację", openNavigation: "Otwórz nawigację", useLightTheme: "Użyj jasnego motywu", useDarkTheme: "Użyj ciemnego motywu", navigation: "Nawigacja Domen KmerHosting" },
  fa: { overview: "نمای کلی", domains: "دامنه‌ها", orders: "سفارش‌ها", contacts: "مخاطبان", invoices: "فاکتورها", profile: "پروفایل", search: "جستجو", pricing: "قیمت‌گذاری", allTlds: "همه TLDها", features: "ویژگی‌ها", sharedHosting: "میزبانی اشتراکی", transfer: "انتقال", notifications: "اعلان‌ها", account: "حساب", accountMenu: "منوی حساب", connectedServices: "خدمات متصل", customerDashboard: "داشبورد مشتری", centralAccount: "حساب مرکزی", signOut: "خروج", domainAccount: "حساب دامنه", sessionActive: "نشست سرویس دامنه شما فعال است.", centralAccess: "برای دسترسی به خدمات دامنه از حساب مرکزی خود استفاده کنید.", closeNavigation: "بستن پیمایش", openNavigation: "باز کردن پیمایش", useLightTheme: "استفاده از پوسته روشن", useDarkTheme: "استفاده از پوسته تیره", navigation: "پیمایش دامنه‌های KmerHosting" },
};

export function domainShellCopy(locale: unknown) {
  const normalized = normalizeLocale(locale) || "en";
  return { ...COMMON_MESSAGES[normalized], ...messages[normalized] };
}

export function useDomainCopy() {
  const [locale, setLocale] = useState<KmerLocale>(() => normalizeLocale(typeof document === "undefined" ? "en" : document.documentElement.lang) || "en");
  useEffect(() => {
    const onChange = (event: Event) => setLocale(normalizeLocale(event instanceof CustomEvent ? event.detail : document.documentElement.lang) || "en");
    window.addEventListener("kmerhosting:language-change", onChange);
    return () => window.removeEventListener("kmerhosting:language-change", onChange);
  }, []);
  return domainShellCopy(locale);
}
