import { LOCALES, normalizeLocale, type KmerLocale } from "@kmerhosting/i18n";
import { useEffect, useState } from "react";

export type DomainManageCopy = {
  management: string; loading: string; unable: string; manageIntro: string; testDomain: string; testDomainIntro: string;
  status: string; lastSynchronized: string; expires: string; lock: string; privacy: string; autoRenew: string; enabled: string; disabled: string;
  refreshStatus: string; dnsNameservers: string; securityTransfer: string; changesDelay: string; registrarLock: string; unlocked: string; locked: string;
  protectTransfers: string; whoisPrivacy: string; hideContacts: string; revealTransfer: string; revealCode: string; keepPrivate: string; cancel: string;
  renewalRestoration: string; checkQuote: string; quoteIntro: string; restoration: string; restorationUnavailable: string; unavailable: string;
  renewal: string; chargeBalance: string; queueTest: string; orderQueued: string; openOrders: string; transferStatus: string; transferIntro: string;
  transferAction: string; continueLabel: string; confirmAction: string; query: string; approve: string; reject: string; transferCancel: string; working: string;
};

const en: DomainManageCopy = {
  management:"Domain management", loading:"Loading domain data.", unable:"Unable to load this domain.", manageIntro:"Manage DNS, security, contacts and renewal.", testDomain:"Test domain", testDomainIntro:"Changes in this environment do not affect a live domain or your KmerHosting account balance.", status:"Domain status", lastSynchronized:"Last synchronized", expires:"Expires", lock:"Lock", privacy:"Privacy", autoRenew:"Auto-renew", enabled:"Enabled", disabled:"Disabled", refreshStatus:"Refresh domain status", dnsNameservers:"DNS and nameservers", securityTransfer:"Security and transfer code", changesDelay:"Changes may take a moment to appear.", registrarLock:"Registrar lock", unlocked:"Unlocked", locked:"Locked", protectTransfers:"Protect the domain from unauthorized transfers.", whoisPrivacy:"WHOIS privacy", hideContacts:"Hide contact details where supported.", revealTransfer:"Reveal transfer code", revealCode:"Reveal code", keepPrivate:"Show the transfer authorization code. Keep it private.", cancel:"Cancel", renewalRestoration:"Renewal and restoration", checkQuote:"Check renewal quote", quoteIntro:"Check whether renewal is available and see the current price.", restoration:"Domain restoration", restorationUnavailable:"Restoration is not currently available for this domain.", unavailable:"Currently unavailable", renewal:"year renewal", chargeBalance:"Charge central balance and confirm", queueTest:"Queue OTE test order", orderQueued:"Order queued", openOrders:"Open orders", transferStatus:"Transfer status", transferIntro:"Query or act on a pending incoming/outgoing transfer.", transferAction:"Transfer action", continueLabel:"Continue", confirmAction:"Confirm", query:"query", approve:"approve", reject:"reject", transferCancel:"cancel", working:"Working…"
};

const overrides: Partial<Record<KmerLocale, Partial<DomainManageCopy>>> = {
  fr:{management:"Gestion du domaine",loading:"Chargement des données du domaine.",unable:"Impossible de charger ce domaine.",manageIntro:"Gérez le DNS, la sécurité, les contacts et le renouvellement.",testDomain:"Domaine de test",testDomainIntro:"Les changements dans cet environnement n’affectent pas un domaine réel ni le solde de votre compte KmerHosting.",status:"État du domaine",lastSynchronized:"Dernière synchronisation",expires:"Expire le",lock:"Verrouillage",privacy:"Confidentialité",autoRenew:"Renouvellement automatique",enabled:"Activé",disabled:"Désactivé",refreshStatus:"Actualiser l’état du domaine",dnsNameservers:"DNS et serveurs de noms",securityTransfer:"Sécurité et code de transfert",changesDelay:"Les changements peuvent prendre un moment à apparaître.",registrarLock:"Verrouillage du registrar",unlocked:"Déverrouillé",locked:"Verrouillé",protectTransfers:"Protège le domaine contre les transferts non autorisés.",whoisPrivacy:"Confidentialité WHOIS",hideContacts:"Masque les coordonnées lorsque cela est pris en charge.",revealTransfer:"Afficher le code de transfert",revealCode:"Afficher le code",keepPrivate:"Affichez le code d’autorisation de transfert. Gardez-le privé.",cancel:"Annuler",renewalRestoration:"Renouvellement et restauration",checkQuote:"Vérifier le devis de renouvellement",quoteIntro:"Vérifiez si le renouvellement est disponible et consultez le prix actuel.",restoration:"Restauration du domaine",restorationUnavailable:"La restauration n’est pas disponible pour ce domaine.",unavailable:"Actuellement indisponible",renewal:"an de renouvellement",chargeBalance:"Débiter le solde central et confirmer",queueTest:"Mettre en file la commande OTE",orderQueued:"Commande en file",openOrders:"Ouvrir les commandes",transferStatus:"État du transfert",transferIntro:"Interrogez ou agissez sur un transfert entrant ou sortant en attente.",transferAction:"Action de transfert",continueLabel:"Continuer",confirmAction:"Confirmer",working:"Traitement…"},
  es:{management:"Gestión del dominio",loading:"Cargando los datos del dominio.",unable:"No se puede cargar este dominio.",manageIntro:"Gestiona DNS, seguridad, contactos y renovación.",status:"Estado del dominio",expires:"Caduca",refreshStatus:"Actualizar estado del dominio",dnsNameservers:"DNS y servidores de nombres",securityTransfer:"Seguridad y código de transferencia",renewalRestoration:"Renovación y restauración",checkQuote:"Comprobar precio de renovación",restoration:"Restauración del dominio",unavailable:"No disponible actualmente",cancel:"Cancelar",openOrders:"Abrir pedidos",transferStatus:"Estado de la transferencia",continueLabel:"Continuar",working:"Procesando…"},
  pt:{management:"Gestão do domínio",loading:"A carregar os dados do domínio.",unable:"Não foi possível carregar este domínio.",manageIntro:"Gira DNS, segurança, contactos e renovação.",status:"Estado do domínio",expires:"Expira",refreshStatus:"Atualizar estado do domínio",dnsNameservers:"DNS e servidores de nomes",securityTransfer:"Segurança e código de transferência",renewalRestoration:"Renovação e restauração",checkQuote:"Verificar preço da renovação",restoration:"Restauração do domínio",unavailable:"Indisponível atualmente",cancel:"Cancelar",openOrders:"Abrir pedidos",transferStatus:"Estado da transferência",continueLabel:"Continuar",working:"A processar…"},
  de:{management:"Domainverwaltung",loading:"Domaindaten werden geladen.",unable:"Diese Domain konnte nicht geladen werden.",manageIntro:"DNS, Sicherheit, Kontakte und Verlängerung verwalten.",status:"Domainstatus",expires:"Läuft ab",refreshStatus:"Domainstatus aktualisieren",dnsNameservers:"DNS und Nameserver",securityTransfer:"Sicherheit und Transfercode",renewalRestoration:"Verlängerung und Wiederherstellung",checkQuote:"Verlängerungspreis prüfen",restoration:"Domainwiederherstellung",unavailable:"Derzeit nicht verfügbar",cancel:"Abbrechen",openOrders:"Bestellungen öffnen",transferStatus:"Transferstatus",continueLabel:"Weiter",working:"Wird verarbeitet…"},
  "zh-Hans":{management:"域名管理",loading:"正在加载域名数据。",unable:"无法加载此域名。",manageIntro:"管理 DNS、安全、联系人和续费。",status:"域名状态",expires:"到期时间",refreshStatus:"刷新域名状态",dnsNameservers:"DNS 和名称服务器",securityTransfer:"安全与转移代码",renewalRestoration:"续费与恢复",checkQuote:"查看续费报价",restoration:"域名恢复",unavailable:"当前不可用",cancel:"取消",openOrders:"打开订单",transferStatus:"转移状态",continueLabel:"继续",working:"处理中…"},
  ar:{management:"إدارة النطاق",loading:"جارٍ تحميل بيانات النطاق.",unable:"تعذر تحميل هذا النطاق.",manageIntro:"إدارة DNS والأمان وجهات الاتصال والتجديد.",status:"حالة النطاق",expires:"ينتهي",refreshStatus:"تحديث حالة النطاق",dnsNameservers:"DNS وخوادم الأسماء",securityTransfer:"الأمان ورمز النقل",renewalRestoration:"التجديد والاستعادة",checkQuote:"تحقق من عرض التجديد",restoration:"استعادة النطاق",unavailable:"غير متاح حاليًا",cancel:"إلغاء",openOrders:"فتح الطلبات",transferStatus:"حالة النقل",continueLabel:"متابعة",working:"جارٍ المعالجة…"},
  hi:{management:"डोमेन प्रबंधन",loading:"डोमेन डेटा लोड हो रहा है।",unable:"यह डोमेन लोड नहीं हो सका।",manageIntro:"DNS, सुरक्षा, संपर्क और नवीनीकरण प्रबंधित करें।",status:"डोमेन स्थिति",expires:"समाप्ति",refreshStatus:"डोमेन स्थिति रीफ़्रेश करें",dnsNameservers:"DNS और नेमसर्वर",securityTransfer:"सुरक्षा और ट्रांसफ़र कोड",renewalRestoration:"नवीनीकरण और पुनर्स्थापना",checkQuote:"नवीनीकरण मूल्य जाँचें",restoration:"डोमेन पुनर्स्थापना",unavailable:"अभी उपलब्ध नहीं",cancel:"रद्द करें",openOrders:"ऑर्डर खोलें",transferStatus:"ट्रांसफ़र स्थिति",continueLabel:"जारी रखें",working:"प्रोसेस हो रहा है…"},
  bn:{management:"ডোমেইন ব্যবস্থাপনা",loading:"ডোমেইন ডেটা লোড হচ্ছে।",unable:"এই ডোমেইন লোড করা যায়নি।",manageIntro:"DNS, নিরাপত্তা, পরিচিতি ও নবায়ন পরিচালনা করুন।",status:"ডোমেইনের অবস্থা",expires:"মেয়াদ শেষ",refreshStatus:"ডোমেইনের অবস্থা রিফ্রেশ করুন",dnsNameservers:"DNS ও নেমসার্ভার",securityTransfer:"নিরাপত্তা ও ট্রান্সফার কোড",renewalRestoration:"নবায়ন ও পুনরুদ্ধার",checkQuote:"নবায়নের কোট দেখুন",restoration:"ডোমেইন পুনরুদ্ধার",unavailable:"বর্তমানে উপলব্ধ নয়",cancel:"বাতিল",openOrders:"অর্ডার খুলুন",transferStatus:"ট্রান্সফারের অবস্থা",continueLabel:"চালিয়ে যান",working:"প্রক্রিয়াধীন…"},
  id:{management:"Manajemen domain",loading:"Memuat data domain.",unable:"Domain ini tidak dapat dimuat.",manageIntro:"Kelola DNS, keamanan, kontak, dan perpanjangan.",status:"Status domain",expires:"Berakhir",refreshStatus:"Segarkan status domain",dnsNameservers:"DNS dan nameserver",securityTransfer:"Keamanan dan kode transfer",renewalRestoration:"Perpanjangan dan pemulihan",checkQuote:"Periksa harga perpanjangan",restoration:"Pemulihan domain",unavailable:"Saat ini tidak tersedia",cancel:"Batal",openOrders:"Buka pesanan",transferStatus:"Status transfer",continueLabel:"Lanjutkan",working:"Memproses…"},
  ja:{management:"ドメイン管理",loading:"ドメインデータを読み込んでいます。",unable:"このドメインを読み込めません。",manageIntro:"DNS、セキュリティ、連絡先、更新を管理します。",status:"ドメインの状態",expires:"有効期限",refreshStatus:"ドメイン状態を更新",dnsNameservers:"DNS とネームサーバー",securityTransfer:"セキュリティと移管コード",renewalRestoration:"更新と復元",checkQuote:"更新料金を確認",restoration:"ドメイン復元",unavailable:"現在利用できません",cancel:"キャンセル",openOrders:"注文を開く",transferStatus:"移管状況",continueLabel:"続行",working:"処理中…"},
  ru:{management:"Управление доменом",loading:"Загрузка данных домена.",unable:"Не удалось загрузить этот домен.",manageIntro:"Управляйте DNS, безопасностью, контактами и продлением.",status:"Состояние домена",expires:"Истекает",refreshStatus:"Обновить состояние домена",dnsNameservers:"DNS и серверы имён",securityTransfer:"Безопасность и код переноса",renewalRestoration:"Продление и восстановление",checkQuote:"Проверить цену продления",restoration:"Восстановление домена",unavailable:"Сейчас недоступно",cancel:"Отмена",openOrders:"Открыть заказы",transferStatus:"Состояние переноса",continueLabel:"Продолжить",working:"Выполняется…"},
  it:{management:"Gestione dominio",loading:"Caricamento dei dati del dominio.",unable:"Impossibile caricare questo dominio.",manageIntro:"Gestisci DNS, sicurezza, contatti e rinnovo.",status:"Stato del dominio",expires:"Scade",refreshStatus:"Aggiorna stato dominio",dnsNameservers:"DNS e nameserver",securityTransfer:"Sicurezza e codice di trasferimento",renewalRestoration:"Rinnovo e ripristino",checkQuote:"Controlla il preventivo di rinnovo",restoration:"Ripristino dominio",unavailable:"Non disponibile al momento",cancel:"Annulla",openOrders:"Apri ordini",transferStatus:"Stato trasferimento",continueLabel:"Continua",working:"Elaborazione…"},
  ko:{management:"도메인 관리",loading:"도메인 데이터를 불러오는 중입니다.",unable:"이 도메인을 불러올 수 없습니다.",manageIntro:"DNS, 보안, 연락처 및 갱신을 관리합니다.",status:"도메인 상태",expires:"만료",refreshStatus:"도메인 상태 새로 고침",dnsNameservers:"DNS 및 네임서버",securityTransfer:"보안 및 이전 코드",renewalRestoration:"갱신 및 복원",checkQuote:"갱신 견적 확인",restoration:"도메인 복원",unavailable:"현재 사용할 수 없음",cancel:"취소",openOrders:"주문 열기",transferStatus:"이전 상태",continueLabel:"계속",working:"처리 중…"},
  tr:{management:"Alan adı yönetimi",loading:"Alan adı verileri yükleniyor.",unable:"Bu alan adı yüklenemedi.",manageIntro:"DNS, güvenlik, kişiler ve yenilemeyi yönetin.",status:"Alan adı durumu",expires:"Bitiş",refreshStatus:"Alan adı durumunu yenile",dnsNameservers:"DNS ve ad sunucuları",securityTransfer:"Güvenlik ve transfer kodu",renewalRestoration:"Yenileme ve geri yükleme",checkQuote:"Yenileme teklifini kontrol et",restoration:"Alan adı geri yükleme",unavailable:"Şu anda kullanılamıyor",cancel:"İptal",openOrders:"Siparişleri aç",transferStatus:"Transfer durumu",continueLabel:"Devam",working:"İşleniyor…"},
  vi:{management:"Quản lý tên miền",loading:"Đang tải dữ liệu tên miền.",unable:"Không thể tải tên miền này.",manageIntro:"Quản lý DNS, bảo mật, liên hệ và gia hạn.",status:"Trạng thái tên miền",expires:"Hết hạn",refreshStatus:"Làm mới trạng thái tên miền",dnsNameservers:"DNS và nameserver",securityTransfer:"Bảo mật và mã chuyển",renewalRestoration:"Gia hạn và khôi phục",checkQuote:"Kiểm tra báo giá gia hạn",restoration:"Khôi phục tên miền",unavailable:"Hiện không khả dụng",cancel:"Hủy",openOrders:"Mở đơn hàng",transferStatus:"Trạng thái chuyển",continueLabel:"Tiếp tục",working:"Đang xử lý…"},
  ur:{management:"ڈومین کا انتظام",loading:"ڈومین کا ڈیٹا لوڈ ہو رہا ہے۔",unable:"یہ ڈومین لوڈ نہیں ہو سکا۔",manageIntro:"DNS، سیکیورٹی، رابطوں اور تجدید کا انتظام کریں۔",status:"ڈومین کی حالت",expires:"میعاد",refreshStatus:"ڈومین کی حالت تازہ کریں",dnsNameservers:"DNS اور نیم سرورز",securityTransfer:"سیکیورٹی اور منتقلی کوڈ",renewalRestoration:"تجدید اور بحالی",checkQuote:"تجدید کا تخمینہ دیکھیں",restoration:"ڈومین کی بحالی",unavailable:"فی الحال دستیاب نہیں",cancel:"منسوخ",openOrders:"آرڈرز کھولیں",transferStatus:"منتقلی کی حالت",continueLabel:"جاری رکھیں",working:"کارروائی جاری ہے…"},
  nl:{management:"Domeinbeheer",loading:"Domeingegevens laden.",unable:"Dit domein kan niet worden geladen.",manageIntro:"Beheer DNS, beveiliging, contacten en verlenging.",status:"Domeinstatus",expires:"Verloopt",refreshStatus:"Domeinstatus vernieuwen",dnsNameservers:"DNS en nameservers",securityTransfer:"Beveiliging en verhuiscode",renewalRestoration:"Verlenging en herstel",checkQuote:"Verlengingsprijs controleren",restoration:"Domeinherstel",unavailable:"Momenteel niet beschikbaar",cancel:"Annuleren",openOrders:"Bestellingen openen",transferStatus:"Verhuisstatus",continueLabel:"Doorgaan",working:"Wordt verwerkt…"},
  pl:{management:"Zarządzanie domeną",loading:"Ładowanie danych domeny.",unable:"Nie można załadować tej domeny.",manageIntro:"Zarządzaj DNS, bezpieczeństwem, kontaktami i odnowieniem.",status:"Stan domeny",expires:"Wygasa",refreshStatus:"Odśwież stan domeny",dnsNameservers:"DNS i serwery nazw",securityTransfer:"Bezpieczeństwo i kod transferu",renewalRestoration:"Odnowienie i przywracanie",checkQuote:"Sprawdź wycenę odnowienia",restoration:"Przywracanie domeny",unavailable:"Obecnie niedostępne",cancel:"Anuluj",openOrders:"Otwórz zamówienia",transferStatus:"Stan transferu",continueLabel:"Kontynuuj",working:"Przetwarzanie…"},
  fa:{management:"مدیریت دامنه",loading:"در حال بارگذاری داده‌های دامنه.",unable:"بارگذاری این دامنه ممکن نیست.",manageIntro:"DNS، امنیت، مخاطبان و تمدید را مدیریت کنید.",status:"وضعیت دامنه",expires:"انقضا",refreshStatus:"تازه‌سازی وضعیت دامنه",dnsNameservers:"DNS و نام‌سرورها",securityTransfer:"امنیت و کد انتقال",renewalRestoration:"تمدید و بازیابی",checkQuote:"بررسی قیمت تمدید",restoration:"بازیابی دامنه",unavailable:"در حال حاضر در دسترس نیست",cancel:"لغو",openOrders:"باز کردن سفارش‌ها",transferStatus:"وضعیت انتقال",continueLabel:"ادامه",working:"در حال پردازش…"}
};

export function domainManageCopy(locale: string): DomainManageCopy {
  const code = normalizeLocale(locale) || "en";
  return { ...en, ...(overrides[code as KmerLocale] || {}) };
}

export function useDomainManageCopy() {
  const [locale, setLocale] = useState<KmerLocale>(() => normalizeLocale(typeof document === "undefined" ? "en" : document.documentElement.lang) || "en");
  useEffect(() => { const onChange = (event: Event) => setLocale(normalizeLocale(event instanceof CustomEvent ? event.detail : document.documentElement.lang) || "en"); window.addEventListener("kmerhosting:language-change", onChange); return () => window.removeEventListener("kmerhosting:language-change", onChange); }, []);
  return domainManageCopy(locale);
}
